# Lab 2: Intro to NumPy and Stock Statistics

### Author: Morgan Gladden

## Part A: Intro to NumPy

### Step A

In [1]:
import numpy as np

In [5]:
# iii.
A1 = np.zeros((3, 4), dtype=int)
A1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
# iv.
print(np.ndim(A1))
print(np.shape(A1))
print(np.size(A1))
print(A1.dtype)

2
(3, 4)
12
int32


In [7]:
# v.
A2 = np.add(A1, 5)
A2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
# vi.
A2[2, 1] = 2
A2[1, 2] = 1
A2[0, 3] = 3
A2

array([[5, 5, 5, 3],
       [5, 5, 1, 5],
       [5, 2, 5, 5]])

In [10]:
# vii.
A2[::-1, ::-1]

array([[5, 5, 2, 5],
       [5, 1, 5, 5],
       [3, 5, 5, 5]])

### Step B

In [12]:
# ii.
B1 = np.arange(1, 10)
B1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# iii.
B2, B3, B4 = np.hsplit(B1, [3, 6])
B2

array([1, 2, 3])

In [14]:
B3

array([4, 5, 6])

In [17]:
B4

array([7, 8, 9])

In [18]:
# iv.
B5 = 4 * B4 + 3 * B3 - 2 * B2
B5

array([38, 43, 48])

In [19]:
# v.
print(np.max(B5))
print(np.min(B5))
print(np.sum(B5))

48
38
129


### Step C

In [20]:
# ii.
C1 = np.arange(1, 20, 2)
C1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
# iii.
C2 = np.reshape(C1, (5, 2))
C2

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [30]:
# iv.
C3 = np.sum(C2, axis=1).reshape(5, 1)
C3

array([[ 4],
       [12],
       [20],
       [28],
       [36]])

In [32]:
# v.
C4 = np.concatenate([C2, C3], axis=1)
C4

array([[ 1,  3,  4],
       [ 5,  7, 12],
       [ 9, 11, 20],
       [13, 15, 28],
       [17, 19, 36]])

In [33]:
# vi.
print(np.ndim(C4))
print(np.shape(C4))
print(np.size(C4))
print(C4.dtype)

2
(5, 3)
15
int32


### Step D

In [35]:
# ii.
np.random.seed(0)

# iii.
D = np.random.random((5, 3))
D

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [36]:
# iv.
DM = np.mean(D, axis=0)
DM

array([0.496554  , 0.74958777, 0.56245025])

In [37]:
# v.
DC = np.subtract(D, DM)
DC

array([[ 0.05225951, -0.0343984 ,  0.04031313],
       [ 0.04832919, -0.32593297,  0.08344387],
       [-0.05896678,  0.14218523,  0.40121251],
       [-0.11311248,  0.04213727, -0.03355533],
       [ 0.07149057,  0.17600887, -0.49141419]])

In [38]:
DV = np.mean(DC, axis=0)
DV

array([3.33066907e-17, 4.44089210e-17, 0.00000000e+00])

### Step E

In [43]:
# ii.
np.random.seed(33)

# iii.
E = np.random.randint(1, 9, size=(3, 5))
E

array([[5, 8, 1, 3, 3],
       [2, 2, 4, 7, 6],
       [4, 7, 5, 3, 6]])

In [44]:
# iv.
EM = np.median(E)
EM

4.0

In [45]:
# v.
EML = (E < EM)
EML

array([[False, False,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False,  True, False]])

In [46]:
# vi.
np.sum(EML)

6

In [47]:
# vii.
EMG = (E > EM)
EMG

array([[ True,  True, False, False, False],
       [False, False, False,  True,  True],
       [False,  True,  True, False,  True]])

In [48]:
# viii.
np.sum(EMG)

7

In [49]:
# ix.
EME = (E == EM)
EME

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False, False]])

In [56]:
# x.
np.sum(EME)

2

In [86]:
# xi.
within_one = np.sum((E >= EM -1) & (E <= EM + 1))
within_one

7

In [103]:
# xii.
ES = np.reshape(E, (15,))
ES = np.sort(ES)
ES

array([1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8])

In [107]:
# xiii.
index = [6, 4, 8]
ES[index]

array([4, 3, 5])

### Step F

In [110]:
# ii.
F1 = np.arange(1, 34)
F1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [112]:
# iii.
F2 = np.reshape(F1, (11,3))
F2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [113]:
# iv.
F3 = (F2 % 3 == 0)
F3

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [116]:
# v.
F4 = np.where(F3 == False, 0, 3)
F4

array([[0, 0, 3],
       [0, 0, 3],
       [0, 0, 3],
       [0, 0, 3],
       [0, 0, 3],
       [0, 0, 3],
       [0, 0, 3],
       [0, 0, 3],
       [0, 0, 3],
       [0, 0, 3],
       [0, 0, 3]])

In [120]:
# vi.
F5 = np.transpose(F2)
F5

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33]])

## Part B: Stock Stats

### Step A: Read the Dataset

In [123]:
# Import the needed libraries
import numpy as np
import csv
from math import sqrt

In [124]:
# Read in the stock data 
def read_stock_info(filename):
    """
    1. Use a try/except block and for loops to read the dataset 
       contained in a CSV file and place it in a nested list.  Open 
       the file with the 'with open as' statement, which does not 
       require that you you explicitly close the file. Use the 
       csv.reader function: See the Working With CSV and JSON Modules 
       pdf file. Each inner list holds the data from the line in the 
       file. Each line is like a record from a database table.
       Each element of the list is a field from a database table.
       Each line is has field names of
       ['Date','Open','High','Low','Close','Volume','Name']
    2. You need to strip all whitespace from the Date and Name fields
       You need to convert the prices (Open,High,Low,Close) to floats: 
       and the Volume to an integer
       Traverse each record of the outer list using a for loop
       Convert each field as specified above
    3. Return the converted nested list  
     """
    try:
        # Using 'with open as' keeps you from having 
        # to explicitly close the file object
        with open (filename, 'r') as input_file:
        
            # See CSV JSON pdf file for more informsation
            # about reading CSV files into a Python program.      
            stock_list = csv.reader(input_file)
            stocks_data = list(stock_list)
            
            # Traverse every row (rec) in the nested stock_data list
            for rec in range(len(stocks_data)):
                # Strip whitespace chars from the first 0) and last(6) fields
                for field in [0,6]:
                    stocks_data[rec][field] = stocks_data[rec][field].strip()
                # Convert the stock prices to floats
                for field in range (1, 5):
                    stocks_data[rec][field] = float (stocks_data[rec][field])
                # Convert the volume to integer   
                stocks_data[rec][5] = int(stocks_data[rec][5]) 
    except IOError:
        print("File Not Found Error.")    
    
    return stocks_data

In [125]:
# Read the stock data file
stocks_data = read_stock_info('4stocks_1qtr.csv')
# Print the first 100 stock records
print("\nFirst 10 stock records")
for rec in stocks_data[:10]:
    print(rec)


First 10 stock records
['1/3/2017', 115.8, 116.33, 114.76, 116.15, 28781865, 'AAPL']
['1/4/2017', 115.85, 116.51, 115.75, 116.02, 21118116, 'AAPL']
['1/5/2017', 115.92, 116.86, 115.81, 116.61, 22193587, 'AAPL']
['1/6/2017', 116.78, 118.16, 116.47, 117.91, 31751900, 'AAPL']
['1/9/2017', 117.95, 119.43, 117.94, 118.99, 33561948, 'AAPL']
['1/10/2017', 118.77, 119.38, 118.3, 119.11, 24462051, 'AAPL']
['1/11/2017', 118.74, 119.93, 118.6, 119.75, 27588593, 'AAPL']
['1/12/2017', 118.9, 119.3, 118.21, 119.25, 27086220, 'AAPL']
['1/13/2017', 119.11, 119.62, 118.81, 119.04, 26111948, 'AAPL']
['1/17/2017', 118.34, 120.24, 118.22, 120.0, 34439843, 'AAPL']


### Step B: Get the Month from Date

In [126]:
# Get the month from the date string
# Using the string index method and string slicing
def get_month(date):
    # Use the string index method to find the first '/' in the string
    slash_index = date.index('/')
    
    # Use slicing to grab the characters before the first slash
    month_str = date[0:slash_index]
    
    # Convert the string to integer
    month = int(month_str)
        
    return month    

In [130]:
# Test the function
date  = '1/3/2017'
get_month(date)

1

In [140]:
# Get the month from the date string
# Using the string split method to produce a list
# Convert the first element of the list into an integer
def get_month(date):
    # Use the string split method to split the date into a list of month, day, and year
    string = date.split('/')
    
    # Isolate the month from the list
    month_string = string[0]
    
    # Convert string to an integer
    month = int(month_string)
        
    return month  

In [141]:
# Test the function
date  = '01/03/2017'
month = get_month(date)

### Step C: Calculate Coefficient of Variation

In [142]:
# Calculate the coefficient of variation for the
# given list of values using lists and for loops
def calc_coeff_var(values):
    """
    Calculates the standard deviation from the mean for a list of values
    """
    mean = sum(values) / len(values)
    
    diffs = []
    for x in values:
        diffs.append(x - mean)
        
    squ_diffs = []
    for d in diffs:
        squ_diffs.append(d**2)

    std_dev = sqrt(sum(squ_diffs) / len(values))
    coeff_var = std_dev / mean
    
    return coeff_var

In [143]:
# Test the function
values = [115.8, 116.33, 114.76, 116.15]
calc_coeff_var(values)

0.005252146568184989

In [144]:
# Calculate the coefficient of variation 
# for the given list of values using the given mean
def calc_coeff_var_lc(values):
    """
    Calculates the standard deviation from the mean for a list of values
    """
    #1. mean = sum(values) / len(values)
    #2. diffs = []
    #   for x in values:
    #       diffs.append(x - mean)
    # becomes
    #3. diffs = [x - (sum(values) / len(values)) for x in values]
    
    #4. squ_diffs = []
    #   for d in diffs:
    #       squ_diffs.append(d**2)
    # becomes
    #5. squ_diffs = [d**2 for d in diffs] 
    
    #3. diffs = [x - (sum(values) / len(values)) for x in values]
    #5. squ_diffs = [d**2 for d in diffs]
    # becomes
    #6. squ_diffs = [d**2 for d in [x - (sum(values) / len(values)) 
    #               for x in values]]
    
    #6. squ_diffs = [d**2 for d in [x - (sum(values) / len(values)) 
    #               for x in values]]
    #7. std_dev = sqrt(sum(squ_diffs) / len(values))
    # becomes
    #8. std_dev = sqrt(sum([d ** 2 for d in [x - (sum(values) 
    #             / len(values)) for x in values]]) / len(values)) 
    
    # Change sum function argument to a generator express
    #9. std_dev = sqrt(sum(d ** 2 for d in [x - (sum(values) 
    #             / len(values)) for x in values]) / len(values))
    #10.  coeff_var = std_dev / mean 
    # becomes
    
    coeff_var = sqrt(sum(d ** 2 for d in [x - sum(values) 
                      / len(values) for x in values]) 
                      / len(values)) / (sum(values) / len(values))
    return coeff_var

In [145]:
# Test the function
values = [115.8, 116.33, 114.76, 116.15]
calc_coeff_var_lc (values)

0.005252146568184989

In [54]:
# Calculate the coefficient of variation for the
# given list of values using just NumPy constructs
def calc_coeff_var_np(values):
    
    ## Add your code here ##
    
    return coeff_var

In [ ]:
# Test the function
values = [115.8, 116.33, 114.76, 116.15]
calc_coeff_var_np(values)

### Step D: Modify the Stocks Data Nested List

In [56]:
# rec: ['Date', Open, High, Low, Close, Volume, 'Name']
# Replace the 'Date' Field with the 'Month' field
# Add the 'CoeffVar' Field before the 'Volume' field
# New rec: [Month, Open, High, Low, Close, 
#           CoeffVar, Volume, 'Name']
def modify_stocks_data(stocks_data):    
        
    ## Add your code here ##
        
    return stocks_data      

In [ ]:
# Modify the stock_data nested list
stocks_data = modify_stocks_data(stocks_data)

# Print the first 10 stock records
print( "\nFirst 10 stock records")
for rec in stocks_data[:10]:
    print(rec)

### Step E: Create Sorted Stock List

In [58]:
# Create a unique list of the stock names by extracting
# the names from the last field in each record.
# A list of all the values is created using a list comprehension.  
# Next, the Numpy unique function is used to create 
# a smaller sorted list of unique names.
def get_sorted_stock_list_np(stocks_data):
   
    stock_list = [rec[-1] for rec in stocks_data]
    stock_list = list(np.unique(stock_list))
    return stock_list

In [ ]:
# Print the sorted stock names
stock_list = get_sorted_stock_list_np(stocks_data)

print("\nSorted Stock List\n")
print(stock_list) 

In [60]:
# Create a set of the stock names by reading each record 
# in the stocks_data nested list
# Convert the set to a list and sort the list
def get_sorted_stock_list_sc(stocks_data):
    
    ## Add your code here ##
    
    return stock_list

In [ ]:
# Print the sorted stock names
stock_list = get_sorted_stock_list_sc(stocks_data)

print("\nSorted Stock List\n")
print(stock_list) 

### Step F: Extract Only One Stock from the Nested List

In [62]:
# Rec: [Month, Open, High, Low, Close, 
#           CoeffVar, Volume, 'Name']
# Extract from the stocks_data nested list only 
# those records pertaining to a particular stock
# Use for loops and remove the stock Name from the record
# New Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]
def extract_stock(stocks_data, stock):
    
    stock_data = []
    
    for rec in stocks_data:
        if rec[-1] == stock:
            stock_data.append(rec[:-1])
    
    return stock_data

In [ ]:
# Extract the particular stock data
stock = 'AAPL'
print("Stock Data For", stock)
stock_data = extract_stock(stocks_data, stock)

# Print ten records
print("\nFirst 10 stock records")
for rec in stock_data[:10]:
    print(rec)

In [64]:
# Rec: [Month, Open, High, Low, Close, 
#           CoeffVar, Volume, 'Name']
# Extract from the stocks_data nested list only 
# those records pertaining to a particular stock
# Use a list comprehension and remove the stock Name
# from the record
# New Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]
def extract_stock_lc (stocks_data, stock):
       
    ## Add your code here ##
    
    return stock_data

In [ ]:
# Extract the particular stock data
stock = 'AAPL'
print("Stock Data For", stock)
stock_data = extract_stock_lc(stocks_data, stock)

# Print ten records
print("\nFirst 10 stock records")
for rec in stock_data[:10]:
    print(rec)                                                                                                                 

### Step G: Extract Only One Month from the Stock Nested List

In [66]:
# Extract from the stock_data nested list for the particular stock
# only those records pertaining to a particular month, 
# using list comprehension
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]
def extract_month_lc (stock_data, month): 
    
    stock_mon_data = [rec for rec in stock_data if rec[0] == month]    
    
    return stock_mon_data

In [ ]:
# Test the function
# Extract the particular stock month data
month = 1
stock_mon_data = extract_month_lc(stock_data, month)

# Print ten records
print ("\nFirst 10 stock records")
for rec in stock_mon_data[:10]:
    print(rec)

In [68]:
# Extract from the stock_data nested list for the particular stock
# only those records pertaining to a particular month, 
# using lists and for loops
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]
def extract_month(stock_data, month):
            
    ## Add your code here ##
    
    return stock_mon_data

In [ ]:
# Test the function
# Extract the particular stock month data
month = 1
stock_mon_data = extract_month(stock_data, month)

# Print ten records
print("\nFirst 10 stock records")
for rec in stock_mon_data[:10]:
    print(rec)

### Step H: Calculate the Stock Statistics and Place in Nested List

In [70]:
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]
# Calculate the stock stats for each stock 
# and place them in a nested list:
# ['Name', JanPerf, JanVol, FebPerf, FebVol, 
#          MarPerf, MarVol, QtrPerf, QtrVol]
def calc_stock_stats(stocks_data):
    stocks_stats = []
    
    # Get Sorted Stock List
    stock_list = get_sorted_stock_list_np(stocks_data)
    
    # Traverse Stock List ['AAPL', 'GOOGL', IBM', 'ORCL'] to 
    # Extract All Stock Rows
    for stock in stock_list:
        
        stock_stats = []
        
        # Build Stock_Stats inner list
        stock_stats.append(stock)
        
        # Get All Rows Pertaining to a Certain Stock
        stock_data = extract_stock(stocks_data, stock)
        
        # Convert the Nested List into a NumPy Array
        qtr_array = np.array(stock_data)
        
        # Calculate Stock Volatility For Quarter
        # Grab the CoeffVar column for the stock
        # All rows and sixth column
        cov_col = qtr_array[:, 5]
        
        # Find the average of the CoeffVar column
        qtr_volatility = np.mean(cov_col) 
        
        # Calculate the Quarter Performance For the Stock
        # Get the index of the last row in CoeffVar column
        last_row = cov_col.size - 1
        
        # Get the price of the stock at the start of the quarter
        # First row and second column 
        open_qtr = qtr_array[0, 1]
        
        # Get the price of the stock at the end of the quarter
        # Last row and fifth column 
        close_qtr = qtr_array[last_row, 4]
        
        # Calculate the stock performance for the quarter
        qtr_perf = (close_qtr - open_qtr) / open_qtr
            
        # For Each Month in the Quarter
        for month in range(1,4):
            
            # Get All Rows Pertaining to a Certain Stock and Month
            stock_mon_data = extract_month_lc(stock_data, month)
            
            # Convert the Nested List into a NumPy Array
            month_array = np.array(stock_mon_data)
            
            # Calculate Stock Volatility For Month
            # Grab the CoeffVar column for the stock
            # All rows and sixth column
            cov_col = month_array[:, 5]
            
            # Find the average of the CoeffVar column
            mon_volatility = np.mean(cov_col)     
            
            # Calculate the Month Performance For the Stock
            # Get the index of the last row in CoeffVar column
            last_row = cov_col.size - 1
            
            # Get the price of the stock at the start of the month
            # First row and second column
            open_mon = month_array[0, 1]
            
            # Get the price of the stock at the end of the month
            # Last row and fifth column
            close_mon = month_array[last_row, 4]
            
            # Calculate the stock performance for the month
            mon_perf = (close_mon - open_mon) / open_mon
            
            # Build Stock_Stats month inner list
            stock_stats.append(mon_perf)
            stock_stats.append(mon_volatility)
            
        # Build Stock_Stats quarter inner list
        stock_stats.append(qtr_perf)
        stock_stats.append(qtr_volatility)
        
        # Build Stock_Stats nested list
        stocks_stats.append(stock_stats)
        
    return stocks_stats        

In [ ]:
# Run the function to produce the stock_stats nested list
stock_stats = calc_stock_stats(stocks_data)

print("\nStock records")
for rec in stock_stats:
    print(rec)
    print()

In [72]:
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]
# Calculate the stock stats for each stock 
# and place them in a nested list:
# ['Name', JanPerf, JanVol, FebPerf, FebVol, 
#          MarPerf, MarVol, QtrPerf, QtrVol]
def calc_stock_stats(stocks_data):
    
    ## Add your code here ##
        
    return stocks_stats        

In [ ]:
# Run the function to produce the stock_stats nested list
stock_stats = calc_stock_stats(stocks_data)

print("\nStock records")
for rec in stock_stats:
    print(rec)
    print()

### Step I: Print the Stock Statistics

In [74]:
# Print the stock stats for each stock 
# ['Name', JanPerf, JanVol, FebPerf, FebVol, 
#          MarPerf, MarVol, QtrPerf, QtrVol]
def print_stock_stats(stock_stats):
    for stock in stock_stats:
        print("Statistics For", stock[0])
        print("Jan Perfomance", '{:6.4f}'.format(stock[1]), 
              "Jan Volatility", '{:8.6f}'.format(stock[2]))
        print("Feb Perfomance", '{:6.4f}'.format(stock[3]), 
              "Feb Volatility", '{:8.6f}'.format(stock[4]))
        print("Mar Perfomance", '{:6.4f}'.format(stock[5]), 
              "Mar Volatility", '{:8.6f}'.format(stock[6]))
        print("1st Qtr Perfomance", '{:6.4f}'.format(stock[7]), 
              "1st Qtr Volatility", '{:8.6f}'.format(stock[8]))
        print ()

In [ ]:
# Print the Stock Statistics for comparison
print_stock_stats (stock_stats)

### Step J: Fill in Table With Stock Name